import { GamedayReport } from './types';

export const data: GamedayReport = {
  gameInfo: {
    gamePk: 778025,
    gameDateStr: 'Tuesday, May 6',
    gameTimeStr: '9:38pm',
    homeTeam: {
      id: 108,
      name: 'Angels',
      abbreviation: 'LAA',
      wins: 13,
      losses: 20,
    },
    awayTeam: {
      id: 141,
      name: 'Blue Jays',
      abbreviation: 'TOR',
      wins: 16,
      losses: 18,
    },
    isJaysHome: false,
  },
  teamStats: {
    blueJaysAbbr: 'TOR',
    opponentAbbr: 'LAA',
    last5Scores: [
      {
        gameDate: '2025-05-04T17:37:00Z',
        blueJaysScore: 4,
        opponentScore: 5,
        opponentAbbr: 'CLE',
      },
      {
        gameDate: '2025-05-03T19:07:00Z',
        blueJaysScore: 3,
        opponentScore: 5,
        opponentAbbr: 'CLE',
      },
      {
        gameDate: '2025-05-02T23:07:00Z',
        blueJaysScore: 5,
        opponentScore: 3,
        opponentAbbr: 'CLE',
      },
      {
        gameDate: '2025-05-01T23:07:00Z',
        blueJaysScore: 4,
        opponentScore: 2,
        opponentAbbr: 'BOS',
      },
      {
        gameDate: '2025-04-30T23:07:00Z',
        blueJaysScore: 7,
        opponentScore: 6,
        opponentAbbr: 'BOS',
      },
    ],
    avgScoresLast10: {
      jays: 3.3,
      opponent: 5.2,
    },
    avgScoresSeason: {
      jays: 3.5294117647058822,
      opponent: 4.5,
    },
  },
  pitchers: {
    home: {
      playerId: 542881,
      name: 'Anderson',
      wins: 2,
      losses: 0,
      era: '2.67',
    },
    away: {
      playerId: 570632,
      name: 'Ureña',
      wins: 0,
      losses: 0,
      era: '15.00',
    },
  },
  battingOrder: [
    {
      playerId: 666182,
      battingOrder: 1,
      name: 'Bichette',
      avgLast10: 0.2857142857142857,
      avgSeason: 0.3028169014084507,
      avgLast10Trending: 'down',
    },
    {
      playerId: 665489,
      battingOrder: 2,
      name: 'Guerrero Jr.',
      avgLast10: 0.2631578947368421,
      avgSeason: 0.27419354838709675,
      avgLast10Trending: 'down',
    },
    {
      playerId: 623993,
      battingOrder: 3,
      name: 'Santander',
      avgLast10: 0.13513513513513514,
      avgSeason: 0.184,
      avgLast10Trending: 'down',
    },
    {
      playerId: 543807,
      battingOrder: 4,
      name: 'Springer',
      avgLast10: 0.22580645161290322,
      avgSeason: 0.3,
      avgLast10Trending: 'down',
    },
    {
      playerId: 672386,
      battingOrder: 5,
      name: 'Kirk',
      avgLast10: 0.28205128205128205,
      avgSeason: 0.25,
      avgLast10Trending: 'up',
    },
    {
      playerId: 662139,
      battingOrder: 6,
      name: 'Varsho',
      avgLast10: 0.21428571428571427,
      avgSeason: 0.21428571428571427,
      avgLast10Trending: 'neutral',
    },
    {
      playerId: 676391,
      battingOrder: 7,
      name: 'Clement',
      avgLast10: 0.2413793103448276,
      avgSeason: 0.2125,
      avgLast10Trending: 'up',
    },
    {
      playerId: 664702,
      battingOrder: 8,
      name: 'Straw',
      avgLast10: 0.15789473684210525,
      avgSeason: 0.2692307692307692,
      avgLast10Trending: 'down',
    },
    {
      playerId: 665926,
      battingOrder: 9,
      name: 'Giménez',
      avgLast10: 0.1935483870967742,
      avgSeason: 0.17647058823529413,
      avgLast10Trending: 'up',
    },
  ],
  firstPitch: {
    playerId: 666182,
    batterName: 'Bichette',
    last10: {
      opportunities: 10,
      swingPercentage: 0.3,
      singlePercentage: 0,
      extraBaseHitPercentage: 0.1,
    },
    season: {
      opportunities: 33,
      swingPercentage: 0.3939393939393939,
      singlePercentage: 0.030303030303030304,
      extraBaseHitPercentage: 0.06060606060606061,
    },
  },
  rankings: {
    homeruns: [
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 3,
        statSeason: 4,
        trending: 'up',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 2,
        statSeason: 4,
        trending: 'up',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 2,
        statSeason: 2,
        trending: 'neutral',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 1,
        statSeason: 3,
        trending: 'neutral',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 1,
        statSeason: 2,
        trending: 'up',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 1,
        statSeason: 1,
        trending: 'up',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 0,
        statSeason: 2,
        trending: 'down',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
    ],
    rbi: [
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 8,
        statSeason: 17,
        trending: 'up',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 6,
        statSeason: 11,
        trending: 'up',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 4,
        statSeason: 12,
        trending: 'up',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 3,
        statSeason: 3,
        trending: 'neutral',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 2,
        statSeason: 12,
        trending: 'down',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 2,
        statSeason: 9,
        trending: 'down',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 1,
        statSeason: 14,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 5,
        trending: 'down',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 0,
        statSeason: 3,
        trending: 'down',
      },
    ],
    twoPlusHitGames: [
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 4,
        statSeason: 14,
        trending: 'down',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 4,
        statSeason: 8,
        trending: 'up',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 2,
        statSeason: 5,
        trending: 'up',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 1,
        statSeason: 11,
        trending: 'down',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 1,
        statSeason: 8,
        trending: 'down',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 1,
        statSeason: 4,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 1,
        statSeason: 3,
        trending: 'up',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 1,
        statSeason: 3,
        trending: 'down',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 1,
        statSeason: 1,
        trending: 'neutral',
      },
    ],
    twoPlusBaseGames: [
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 6,
        statSeason: 18,
        trending: 'up',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 4,
        statSeason: 15,
        trending: 'down',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 4,
        statSeason: 14,
        trending: 'down',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 4,
        statSeason: 8,
        trending: 'up',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 3,
        statSeason: 10,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 3,
        statSeason: 6,
        trending: 'up',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 2,
        statSeason: 8,
        trending: 'down',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 2,
        statSeason: 2,
        trending: 'neutral',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 1,
        statSeason: 4,
        trending: 'down',
      },
    ],
    threePlusHitGames: [
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 1,
        statSeason: 2,
        trending: 'up',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 1,
        statSeason: 1,
        trending: 'up',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 0,
        statSeason: 4,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 2,
        trending: 'down',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
    ],
    threePlusBaseGames: [
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 3,
        statSeason: 9,
        trending: 'up',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 3,
        statSeason: 8,
        trending: 'up',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 3,
        statSeason: 6,
        trending: 'up',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 3,
        statSeason: 4,
        trending: 'up',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 2,
        statSeason: 8,
        trending: 'down',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 2,
        statSeason: 2,
        trending: 'neutral',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 1,
        statSeason: 3,
        trending: 'down',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 0,
        statSeason: 4,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 2,
        trending: 'down',
      },
    ],
    twoPlusRbiGames: [
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 3,
        statSeason: 4,
        trending: 'up',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 2,
        statSeason: 3,
        trending: 'up',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 1,
        statSeason: 3,
        trending: 'up',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 1,
        statSeason: 2,
        trending: 'up',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 1,
        statSeason: 1,
        trending: 'neutral',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 0,
        statSeason: 2,
        trending: 'down',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 0,
        statSeason: 2,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
    ],
    threePlusRbiGames: [
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 1,
        statSeason: 2,
        trending: 'up',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 1,
        statSeason: 1,
        trending: 'up',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
    ],
    doubles: [
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 3,
        statSeason: 11,
        trending: 'down',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 3,
        statSeason: 7,
        trending: 'up',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 2,
        statSeason: 4,
        trending: 'up',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 1,
        statSeason: 5,
        trending: 'down',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 1,
        statSeason: 3,
        trending: 'down',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 1,
        statSeason: 2,
        trending: 'up',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 0,
        statSeason: 5,
        trending: 'down',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 0,
        statSeason: 3,
        trending: 'down',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
    ],
    triples: [
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
    ],
    stolenBases: [
      {
        playerId: 665926,
        name: 'Giménez',
        statLast10: 2,
        statSeason: 8,
        trending: 'down',
      },
      {
        playerId: 666182,
        name: 'Bichette',
        statLast10: 2,
        statSeason: 4,
        trending: 'up',
      },
      {
        playerId: 543807,
        name: 'Springer',
        statLast10: 1,
        statSeason: 5,
        trending: 'down',
      },
      {
        playerId: 662139,
        name: 'Varsho',
        statLast10: 1,
        statSeason: 1,
        trending: 'neutral',
      },
      {
        playerId: 664702,
        name: 'Straw',
        statLast10: 0,
        statSeason: 2,
        trending: 'down',
      },
      {
        playerId: 676391,
        name: 'Clement',
        statLast10: 0,
        statSeason: 1,
        trending: 'down',
      },
      {
        playerId: 665489,
        name: 'Guerrero Jr.',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 623993,
        name: 'Santander',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
      {
        playerId: 672386,
        name: 'Kirk',
        statLast10: 0,
        statSeason: 0,
        trending: 'neutral',
      },
    ],
  },
};
