import { GameLineupStats } from './types';

export const data: GameLineupStats = {
  gamePk: 778297,
  gameDate: '2025-04-16T17:07:00Z',
  season: '2025',
  jaysAtHome: true,
  blueJays: {
    team: {
      id: 141,
      name: 'Toronto Blue Jays',
      teamName: 'Blue Jays',
      abbreviation: 'TOR',
    },
    teamStats: {
      seasonStats: {
        wins: 10,
        losses: 8,
        winPercentage: 0.5555555555555556,
        gamesPlayed: 18,
        runsScored: 73,
        runsAllowed: 71,
        avgRunsScoredPerGame: 4.055555555555555,
        avgRunsAllowedPerGame: 3.9444444444444446,
        gameResults: {
          '778311': {
            game: {
              gamePk: 778311,
              gameType: 'R',
              gameDate: '2025-04-15T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 144,
              name: 'Atlanta Braves',
              teamName: 'Braves',
              abbreviation: 'ATL',
            },
            win: true,
            runsScored: 6,
            runsAllowed: 3,
          },
          '778322': {
            game: {
              gamePk: 778322,
              gameType: 'R',
              gameDate: '2025-04-14T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 144,
              name: 'Atlanta Braves',
              teamName: 'Braves',
              abbreviation: 'ATL',
            },
            win: false,
            runsScored: 4,
            runsAllowed: 8,
          },
          '778344': {
            game: {
              gamePk: 778344,
              gameType: 'R',
              gameDate: '2025-04-13T17:35:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: true,
            runsScored: 7,
            runsAllowed: 6,
          },
          '778362': {
            game: {
              gamePk: 778362,
              gameType: 'R',
              gameDate: '2025-04-12T20:05:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: false,
            runsScored: 4,
            runsAllowed: 5,
          },
          '778377': {
            game: {
              gamePk: 778377,
              gameType: 'R',
              gameDate: '2025-04-10T20:10:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: false,
            runsScored: 3,
            runsAllowed: 4,
          },
          '778386': {
            game: {
              gamePk: 778386,
              gameType: 'R',
              gameDate: '2025-04-09T22:45:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: true,
            runsScored: 2,
            runsAllowed: 1,
          },
          '778404': {
            game: {
              gamePk: 778404,
              gameType: 'R',
              gameDate: '2025-04-08T22:45:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: true,
            runsScored: 6,
            runsAllowed: 1,
          },
          '778426': {
            game: {
              gamePk: 778426,
              gameType: 'R',
              gameDate: '2025-04-07T22:45:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: true,
            runsScored: 6,
            runsAllowed: 2,
          },
          '778435': {
            game: {
              gamePk: 778435,
              gameType: 'R',
              gameDate: '2025-04-06T17:40:00Z',
              season: '2025',
            },
            opponent: {
              id: 121,
              name: 'New York Mets',
              teamName: 'Mets',
              abbreviation: 'NYM',
            },
            win: false,
            runsScored: 1,
            runsAllowed: 2,
          },
          '778446': {
            game: {
              gamePk: 778446,
              gameType: 'R',
              gameDate: '2025-04-05T23:10:00Z',
              season: '2025',
            },
            opponent: {
              id: 121,
              name: 'New York Mets',
              teamName: 'Mets',
              abbreviation: 'NYM',
            },
            win: false,
            runsScored: 2,
            runsAllowed: 3,
          },
          '778465': {
            game: {
              gamePk: 778465,
              gameType: 'R',
              gameDate: '2025-04-04T19:10:00Z',
              season: '2025',
            },
            opponent: {
              id: 121,
              name: 'New York Mets',
              teamName: 'Mets',
              abbreviation: 'NYM',
            },
            win: false,
            runsScored: 0,
            runsAllowed: 5,
          },
          '778478': {
            game: {
              gamePk: 778478,
              gameType: 'R',
              gameDate: '2025-04-02T19:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 120,
              name: 'Washington Nationals',
              teamName: 'Nationals',
              abbreviation: 'WSH',
            },
            win: true,
            runsScored: 4,
            runsAllowed: 2,
          },
          '778491': {
            game: {
              gamePk: 778491,
              gameType: 'R',
              gameDate: '2025-04-01T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 120,
              name: 'Washington Nationals',
              teamName: 'Nationals',
              abbreviation: 'WSH',
            },
            win: true,
            runsScored: 5,
            runsAllowed: 3,
          },
          '778507': {
            game: {
              gamePk: 778507,
              gameType: 'R',
              gameDate: '2025-03-31T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 120,
              name: 'Washington Nationals',
              teamName: 'Nationals',
              abbreviation: 'WSH',
            },
            win: true,
            runsScored: 5,
            runsAllowed: 2,
          },
          '778525': {
            game: {
              gamePk: 778525,
              gameType: 'R',
              gameDate: '2025-03-30T17:37:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: true,
            runsScored: 3,
            runsAllowed: 1,
          },
          '778536': {
            game: {
              gamePk: 778536,
              gameType: 'R',
              gameDate: '2025-03-29T19:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: false,
            runsScored: 5,
            runsAllowed: 9,
          },
          '778549': {
            game: {
              gamePk: 778549,
              gameType: 'R',
              gameDate: '2025-03-28T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: true,
            runsScored: 8,
            runsAllowed: 2,
          },
          '778556': {
            game: {
              gamePk: 778556,
              gameType: 'R',
              gameDate: '2025-03-27T19:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: false,
            runsScored: 2,
            runsAllowed: 12,
          },
        },
      },
      statsLast10Games: {
        wins: 5,
        losses: 5,
        winPercentage: 0.5,
        gamesPlayed: 10,
        runsScored: 41,
        runsAllowed: 35,
        avgRunsScoredPerGame: 4.1,
        avgRunsAllowedPerGame: 3.5,
        gameResults: {
          '778311': {
            game: {
              gamePk: 778311,
              gameType: 'R',
              gameDate: '2025-04-15T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 144,
              name: 'Atlanta Braves',
              teamName: 'Braves',
              abbreviation: 'ATL',
            },
            win: true,
            runsScored: 6,
            runsAllowed: 3,
          },
          '778322': {
            game: {
              gamePk: 778322,
              gameType: 'R',
              gameDate: '2025-04-14T23:07:00Z',
              season: '2025',
            },
            opponent: {
              id: 144,
              name: 'Atlanta Braves',
              teamName: 'Braves',
              abbreviation: 'ATL',
            },
            win: false,
            runsScored: 4,
            runsAllowed: 8,
          },
          '778344': {
            game: {
              gamePk: 778344,
              gameType: 'R',
              gameDate: '2025-04-13T17:35:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: true,
            runsScored: 7,
            runsAllowed: 6,
          },
          '778362': {
            game: {
              gamePk: 778362,
              gameType: 'R',
              gameDate: '2025-04-12T20:05:00Z',
              season: '2025',
            },
            opponent: {
              id: 110,
              name: 'Baltimore Orioles',
              teamName: 'Orioles',
              abbreviation: 'BAL',
            },
            win: false,
            runsScored: 4,
            runsAllowed: 5,
          },
          '778377': {
            game: {
              gamePk: 778377,
              gameType: 'R',
              gameDate: '2025-04-10T20:10:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: false,
            runsScored: 3,
            runsAllowed: 4,
          },
          '778386': {
            game: {
              gamePk: 778386,
              gameType: 'R',
              gameDate: '2025-04-09T22:45:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: true,
            runsScored: 2,
            runsAllowed: 1,
          },
          '778404': {
            game: {
              gamePk: 778404,
              gameType: 'R',
              gameDate: '2025-04-08T22:45:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: true,
            runsScored: 6,
            runsAllowed: 1,
          },
          '778426': {
            game: {
              gamePk: 778426,
              gameType: 'R',
              gameDate: '2025-04-07T22:45:00Z',
              season: '2025',
            },
            opponent: {
              id: 111,
              name: 'Boston Red Sox',
              teamName: 'Red Sox',
              abbreviation: 'BOS',
            },
            win: true,
            runsScored: 6,
            runsAllowed: 2,
          },
          '778435': {
            game: {
              gamePk: 778435,
              gameType: 'R',
              gameDate: '2025-04-06T17:40:00Z',
              season: '2025',
            },
            opponent: {
              id: 121,
              name: 'New York Mets',
              teamName: 'Mets',
              abbreviation: 'NYM',
            },
            win: false,
            runsScored: 1,
            runsAllowed: 2,
          },
          '778446': {
            game: {
              gamePk: 778446,
              gameType: 'R',
              gameDate: '2025-04-05T23:10:00Z',
              season: '2025',
            },
            opponent: {
              id: 121,
              name: 'New York Mets',
              teamName: 'Mets',
              abbreviation: 'NYM',
            },
            win: false,
            runsScored: 2,
            runsAllowed: 3,
          },
        },
      },
    },
    batters: [
      {
        battingOrder: 1,
        person: {
          id: 666182,
          fullName: 'Bo Bichette',
          link: '/api/v1/people/666182',
        },
        seasonStats: {
          gamesPlayed: 18,
          firstPitchOfGame: {
            opportunities: 18,
            swings: 8,
            singles: 1,
            extraBaseHits: 1,
            swingPercentage: 0.4444444444444444,
            singlePercentage: 0.05555555555555555,
            extraBaseHitPercentage: 0.05555555555555555,
          },
          atBats: 78,
          hits: 23,
          battingAvg: 0.2948717948717949,
          singles: 17,
          doubles: 6,
          triples: 0,
          homeRuns: 0,
          rbi: 10,
          avgHitsPerGame: 0.9444444444444444,
          avgSinglesPerGame: 0.9444444444444444,
          avgDoublesPerGame: 0.3333333333333333,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 3,
          hitGames03: 3,
          hitGames04: 1,
          hitGames05: 0,
          hitGames02Plus: 7,
          hitGames03Plus: 4,
          hitGames04Plus: 1,
          hitGames05Plus: 0,
          totalBases: 29,
          avgBasesPerGame: 1.6111111111111112,
          baseGames02: 5,
          baseGames03: 1,
          baseGames04: 2,
          baseGames05: 0,
          baseGames06: 1,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 9,
          baseGames03Plus: 4,
          baseGames04Plus: 3,
          baseGames05Plus: 1,
          baseGames06Plus: 1,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 1,
          stolenBases: 0,
          caughtStealing: 1,
          pickoffs: 0,
          stolenBasePercentage: 0,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 10,
            swings: 6,
            singles: 1,
            extraBaseHits: 1,
            swingPercentage: 0.6,
            singlePercentage: 0.1,
            extraBaseHitPercentage: 0.1,
          },
          atBats: 45,
          hits: 14,
          battingAvg: 0.3111111111111111,
          singles: 10,
          doubles: 4,
          triples: 0,
          homeRuns: 0,
          rbi: 7,
          avgHitsPerGame: 1,
          avgSinglesPerGame: 1,
          avgDoublesPerGame: 0.4,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 1,
          hitGames03: 3,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 4,
          hitGames03Plus: 3,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 18,
          avgBasesPerGame: 1.8,
          baseGames02: 3,
          baseGames03: 1,
          baseGames04: 2,
          baseGames05: 0,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 6,
          baseGames03Plus: 3,
          baseGames04Plus: 2,
          baseGames05Plus: 0,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
      },
      {
        battingOrder: 2,
        person: {
          id: 665489,
          fullName: 'Vladimir Guerrero Jr.',
          link: '/api/v1/people/665489',
        },
        seasonStats: {
          gamesPlayed: 18,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 69,
          hits: 19,
          battingAvg: 0.2753623188405797,
          singles: 15,
          doubles: 4,
          triples: 0,
          homeRuns: 0,
          rbi: 8,
          avgHitsPerGame: 0.8333333333333334,
          avgSinglesPerGame: 0.8333333333333334,
          avgDoublesPerGame: 0.2222222222222222,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 6,
          hitGames03: 1,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 7,
          hitGames03Plus: 1,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 23,
          avgBasesPerGame: 1.2777777777777777,
          baseGames02: 6,
          baseGames03: 3,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 9,
          baseGames03Plus: 3,
          baseGames04Plus: 0,
          baseGames05Plus: 0,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 39,
          hits: 11,
          battingAvg: 0.28205128205128205,
          singles: 10,
          doubles: 1,
          triples: 0,
          homeRuns: 0,
          rbi: 5,
          avgHitsPerGame: 1,
          avgSinglesPerGame: 1,
          avgDoublesPerGame: 0.1,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 4,
          hitGames03: 1,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 5,
          hitGames03Plus: 1,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 12,
          avgBasesPerGame: 1.2,
          baseGames02: 3,
          baseGames03: 2,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 5,
          baseGames03Plus: 2,
          baseGames04Plus: 0,
          baseGames05Plus: 0,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
      },
      {
        battingOrder: 3,
        person: {
          id: 623993,
          fullName: 'Anthony Santander',
          link: '/api/v1/people/623993',
        },
        seasonStats: {
          gamesPlayed: 18,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 71,
          hits: 15,
          battingAvg: 0.2112676056338028,
          singles: 10,
          doubles: 3,
          triples: 0,
          homeRuns: 2,
          rbi: 6,
          avgHitsPerGame: 0.5555555555555556,
          avgSinglesPerGame: 0.5555555555555556,
          avgDoublesPerGame: 0.16666666666666666,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.1111111111111111,
          hitGames02: 3,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 3,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 24,
          avgBasesPerGame: 1.3333333333333333,
          baseGames02: 3,
          baseGames03: 1,
          baseGames04: 1,
          baseGames05: 1,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 6,
          baseGames03Plus: 3,
          baseGames04Plus: 2,
          baseGames05Plus: 1,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 41,
          hits: 9,
          battingAvg: 0.21951219512195122,
          singles: 5,
          doubles: 2,
          triples: 0,
          homeRuns: 2,
          rbi: 5,
          avgHitsPerGame: 0.5,
          avgSinglesPerGame: 0.5,
          avgDoublesPerGame: 0.2,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.2,
          hitGames02: 1,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 1,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 17,
          avgBasesPerGame: 1.7,
          baseGames02: 2,
          baseGames03: 0,
          baseGames04: 1,
          baseGames05: 1,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 4,
          baseGames03Plus: 2,
          baseGames04Plus: 2,
          baseGames05Plus: 1,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
      },
      {
        battingOrder: 4,
        person: {
          id: 665926,
          fullName: 'Andrés Giménez',
          link: '/api/v1/people/665926',
        },
        seasonStats: {
          gamesPlayed: 18,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 65,
          hits: 14,
          battingAvg: 0.2153846153846154,
          singles: 8,
          doubles: 3,
          triples: 0,
          homeRuns: 3,
          rbi: 8,
          avgHitsPerGame: 0.4444444444444444,
          avgSinglesPerGame: 0.4444444444444444,
          avgDoublesPerGame: 0.16666666666666666,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.16666666666666666,
          hitGames02: 3,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 3,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 26,
          avgBasesPerGame: 1.4444444444444444,
          baseGames02: 2,
          baseGames03: 1,
          baseGames04: 2,
          baseGames05: 0,
          baseGames06: 1,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 6,
          baseGames03Plus: 4,
          baseGames04Plus: 3,
          baseGames05Plus: 1,
          baseGames06Plus: 1,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 6,
          stolenBases: 5,
          caughtStealing: 1,
          pickoffs: 0,
          stolenBasePercentage: 0.8333333333333334,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 35,
          hits: 6,
          battingAvg: 0.17142857142857143,
          singles: 5,
          doubles: 1,
          triples: 0,
          homeRuns: 0,
          rbi: 2,
          avgHitsPerGame: 0.5,
          avgSinglesPerGame: 0.5,
          avgDoublesPerGame: 0.1,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 2,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 2,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 7,
          avgBasesPerGame: 0.7,
          baseGames02: 1,
          baseGames03: 1,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 2,
          baseGames03Plus: 1,
          baseGames04Plus: 0,
          baseGames05Plus: 0,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 4,
          stolenBases: 4,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: 1,
        },
      },
      {
        battingOrder: 5,
        person: {
          id: 672386,
          fullName: 'Alejandro Kirk',
          link: '/api/v1/people/672386',
        },
        seasonStats: {
          gamesPlayed: 13,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 50,
          hits: 12,
          battingAvg: 0.24,
          singles: 9,
          doubles: 2,
          triples: 0,
          homeRuns: 1,
          rbi: 4,
          avgHitsPerGame: 0.6923076923076923,
          avgSinglesPerGame: 0.6923076923076923,
          avgDoublesPerGame: 0.15384615384615385,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.07692307692307693,
          hitGames02: 5,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 5,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 17,
          avgBasesPerGame: 1.3076923076923077,
          baseGames02: 3,
          baseGames03: 1,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 1,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 5,
          baseGames03Plus: 2,
          baseGames04Plus: 1,
          baseGames05Plus: 1,
          baseGames06Plus: 1,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 39,
          hits: 10,
          battingAvg: 0.2564102564102564,
          singles: 7,
          doubles: 2,
          triples: 0,
          homeRuns: 1,
          rbi: 3,
          avgHitsPerGame: 0.7,
          avgSinglesPerGame: 0.7,
          avgDoublesPerGame: 0.2,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.1,
          hitGames02: 5,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 5,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 15,
          avgBasesPerGame: 1.5,
          baseGames02: 3,
          baseGames03: 1,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 1,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 5,
          baseGames03Plus: 2,
          baseGames04Plus: 1,
          baseGames05Plus: 1,
          baseGames06Plus: 1,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
      },
      {
        battingOrder: 6,
        person: {
          id: 702176,
          fullName: 'Alan Roden',
          link: '/api/v1/people/702176',
        },
        seasonStats: {
          gamesPlayed: 17,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 47,
          hits: 13,
          battingAvg: 0.2765957446808511,
          singles: 9,
          doubles: 3,
          triples: 0,
          homeRuns: 1,
          rbi: 4,
          avgHitsPerGame: 0.5294117647058824,
          avgSinglesPerGame: 0.5294117647058824,
          avgDoublesPerGame: 0.17647058823529413,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.058823529411764705,
          hitGames02: 4,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 4,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 19,
          avgBasesPerGame: 1.1176470588235294,
          baseGames02: 3,
          baseGames03: 1,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 1,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 5,
          baseGames03Plus: 2,
          baseGames04Plus: 1,
          baseGames05Plus: 1,
          baseGames06Plus: 1,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 29,
          hits: 8,
          battingAvg: 0.27586206896551724,
          singles: 5,
          doubles: 2,
          triples: 0,
          homeRuns: 1,
          rbi: 2,
          avgHitsPerGame: 0.5,
          avgSinglesPerGame: 0.5,
          avgDoublesPerGame: 0.2,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.1,
          hitGames02: 3,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 3,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 13,
          avgBasesPerGame: 1.3,
          baseGames02: 1,
          baseGames03: 1,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 1,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 3,
          baseGames03Plus: 2,
          baseGames04Plus: 1,
          baseGames05Plus: 1,
          baseGames06Plus: 1,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
      },
      {
        battingOrder: 7,
        person: {
          id: 676391,
          fullName: 'Ernie Clement',
          link: '/api/v1/people/676391',
        },
        seasonStats: {
          gamesPlayed: 17,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 40,
          hits: 8,
          battingAvg: 0.2,
          singles: 6,
          doubles: 2,
          triples: 0,
          homeRuns: 0,
          rbi: 5,
          avgHitsPerGame: 0.35294117647058826,
          avgSinglesPerGame: 0.35294117647058826,
          avgDoublesPerGame: 0.11764705882352941,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 0,
          hitGames03: 0,
          hitGames04: 1,
          hitGames05: 0,
          hitGames02Plus: 1,
          hitGames03Plus: 1,
          hitGames04Plus: 1,
          hitGames05Plus: 0,
          totalBases: 10,
          avgBasesPerGame: 0.5882352941176471,
          baseGames02: 1,
          baseGames03: 0,
          baseGames04: 0,
          baseGames05: 1,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 2,
          baseGames03Plus: 1,
          baseGames04Plus: 1,
          baseGames05Plus: 1,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 1,
          stolenBases: 1,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: 1,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 26,
          hits: 6,
          battingAvg: 0.23076923076923078,
          singles: 5,
          doubles: 1,
          triples: 0,
          homeRuns: 0,
          rbi: 1,
          avgHitsPerGame: 0.5,
          avgSinglesPerGame: 0.5,
          avgDoublesPerGame: 0.1,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 0,
          hitGames03: 0,
          hitGames04: 1,
          hitGames05: 0,
          hitGames02Plus: 1,
          hitGames03Plus: 1,
          hitGames04Plus: 1,
          hitGames05Plus: 0,
          totalBases: 7,
          avgBasesPerGame: 0.7,
          baseGames02: 0,
          baseGames03: 0,
          baseGames04: 0,
          baseGames05: 1,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 1,
          baseGames03Plus: 1,
          baseGames04Plus: 1,
          baseGames05Plus: 1,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 1,
          stolenBases: 1,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: 1,
        },
      },
      {
        battingOrder: 8,
        person: {
          id: 680718,
          fullName: 'Addison Barger',
          link: '/api/v1/people/680718',
        },
        seasonStats: {
          gamesPlayed: 1,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 4,
          hits: 0,
          battingAvg: 0,
          singles: 0,
          doubles: 0,
          triples: 0,
          homeRuns: 0,
          rbi: 0,
          avgHitsPerGame: 0,
          avgSinglesPerGame: 0,
          avgDoublesPerGame: 0,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 0,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 0,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 0,
          avgBasesPerGame: 0,
          baseGames02: 0,
          baseGames03: 0,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 0,
          baseGames03Plus: 0,
          baseGames04Plus: 0,
          baseGames05Plus: 0,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
        statsLast10Games: {
          gamesPlayed: 1,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 4,
          hits: 0,
          battingAvg: 0,
          singles: 0,
          doubles: 0,
          triples: 0,
          homeRuns: 0,
          rbi: 0,
          avgHitsPerGame: 0,
          avgSinglesPerGame: 0,
          avgDoublesPerGame: 0,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0,
          hitGames02: 0,
          hitGames03: 0,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 0,
          hitGames03Plus: 0,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 0,
          avgBasesPerGame: 0,
          baseGames02: 0,
          baseGames03: 0,
          baseGames04: 0,
          baseGames05: 0,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 0,
          baseGames03Plus: 0,
          baseGames04Plus: 0,
          baseGames05Plus: 0,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 0,
          stolenBases: 0,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: null,
        },
      },
      {
        battingOrder: 9,
        person: {
          id: 664702,
          fullName: 'Myles Straw',
          link: '/api/v1/people/664702',
        },
        seasonStats: {
          gamesPlayed: 13,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 29,
          hits: 11,
          battingAvg: 0.3793103448275862,
          singles: 8,
          doubles: 2,
          triples: 0,
          homeRuns: 1,
          rbi: 3,
          avgHitsPerGame: 0.6153846153846154,
          avgSinglesPerGame: 0.6153846153846154,
          avgDoublesPerGame: 0.15384615384615385,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.07692307692307693,
          hitGames02: 1,
          hitGames03: 1,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 2,
          hitGames03Plus: 1,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 16,
          avgBasesPerGame: 1.2307692307692308,
          baseGames02: 1,
          baseGames03: 0,
          baseGames04: 1,
          baseGames05: 1,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 3,
          baseGames03Plus: 2,
          baseGames04Plus: 2,
          baseGames05Plus: 1,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 1,
          stolenBases: 1,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: 1,
        },
        statsLast10Games: {
          gamesPlayed: 10,
          firstPitchOfGame: {
            opportunities: 0,
            swings: 0,
            singles: 0,
            extraBaseHits: 0,
            swingPercentage: 0,
            singlePercentage: 0,
            extraBaseHitPercentage: 0,
          },
          atBats: 26,
          hits: 11,
          battingAvg: 0.4230769230769231,
          singles: 8,
          doubles: 2,
          triples: 0,
          homeRuns: 1,
          rbi: 3,
          avgHitsPerGame: 0.8,
          avgSinglesPerGame: 0.8,
          avgDoublesPerGame: 0.2,
          avgTriplesPerGame: 0,
          avgHomeRunsPerGame: 0.1,
          hitGames02: 1,
          hitGames03: 1,
          hitGames04: 0,
          hitGames05: 0,
          hitGames02Plus: 2,
          hitGames03Plus: 1,
          hitGames04Plus: 0,
          hitGames05Plus: 0,
          totalBases: 16,
          avgBasesPerGame: 1.6,
          baseGames02: 1,
          baseGames03: 0,
          baseGames04: 1,
          baseGames05: 1,
          baseGames06: 0,
          baseGames07: 0,
          baseGames08: 0,
          baseGames09: 0,
          baseGames10: 0,
          baseGames02Plus: 3,
          baseGames03Plus: 2,
          baseGames04Plus: 2,
          baseGames05Plus: 1,
          baseGames06Plus: 0,
          baseGames07Plus: 0,
          baseGames08Plus: 0,
          baseGames09Plus: 0,
          baseGames10Plus: 0,
          stolenBaseAttempts: 1,
          stolenBases: 1,
          caughtStealing: 0,
          pickoffs: 0,
          stolenBasePercentage: 1,
        },
      },
    ],
    pitchers: [
      {
        pitchingOrder: 1,
        person: {
          id: 605135,
          fullName: 'Chris Bassitt',
          link: '/api/v1/people/605135',
        },
        era: '0.98',
        wins: 1,
        losses: 0,
      },
    ],
  },
  opponent: {
    team: {
      id: 144,
      name: 'Atlanta Braves',
      teamName: 'Braves',
      abbreviation: 'ATL',
    },
    pitchers: [
      {
        pitchingOrder: 1,
        person: {
          id: 675911,
          fullName: 'Spencer Strider',
          link: '/api/v1/people/675911',
        },
        era: '-.--',
        wins: 0,
        losses: 0,
      },
    ],
  },
};
