import GamedayReport from '@/components/GamedayReport';
import { getLatestGamedayReport } from '@/shared/gameday-api';

// prevent this page from being statically generated by vercel build
export const dynamic = 'force-dynamic';

export default async function Index() {
  const report = await getLatestGamedayReport();

  return <GamedayReport report={report} />;
}
