import BattingOrderCard from '@/components/BattingOrderCard';
import FirstPitchCard from '@/components/FirstPitchCard';
import GameInfo from '@/components/GameInfo';
import PitcherMatchupCard from '@/components/PitcherMatchupCard';
import RankingsCard from '@/components/RankingsCard';
import TeamStatsCard from '@/components/TeamStatsCard';
import { getLatestGamedayReport } from '@/shared/gameday-api';
import { Divider, Stack, Typography } from '@mui/material';

// prevent this page from being statically generated by vercel build
export const dynamic = 'force-dynamic';

export default async function Index() {
  const report = await getLatestGamedayReport();

  if (!report) {
    return (
      <Stack spacing={2} alignItems="center" paddingY={4}>
        <Typography variant="h4">Blue Jays Gameday Report</Typography>
        <Typography variant="subtitle1">UH-OH ... SOMETHING WENT WRONG!</Typography>
      </Stack>
    );
  }

  // TODO: add trending to batting order? useful at all?
  // TODO: make stats into tables where applicable
  // TODO: add team wins/losses to game info
  // TODO: add quick links to navigate to a section of the page
  // TODO: add "hot players" to the top of the page; determine from upward trends

  return (
    <Stack spacing={2} width="100%" paddingY={4}>
      <GameInfo gameInfo={report.gameInfo} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <TeamStatsCard teamStats={report.teamStats} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <PitcherMatchupCard pitchers={report.pitchers} gameInfo={report.gameInfo} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <BattingOrderCard battingOrder={report.battingOrder} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <FirstPitchCard firstPitch={report.firstPitch} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="Homeruns" data={report.rankings.homeruns} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="2+ Rbi Games" data={report.rankings.twoPlusRbiGames} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="3+ Rbi Games" data={report.rankings.threePlusRbiGames} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="2+ Hit Games" data={report.rankings.twoPlusHitGames} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="2+ Base Games" data={report.rankings.twoPlusBaseGames} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="3+ Hit Games" data={report.rankings.threePlusHitGames} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="3+ Base Games" data={report.rankings.threePlusBaseGames} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="Doubles" data={report.rankings.doubles} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="Triples" data={report.rankings.triples} />
      <Divider sx={{ py: 1, borderColor: 'grey.500' }} variant="fullWidth" />

      <RankingsCard title="Stolen Bases" data={report.rankings.stolenBases} />
    </Stack>
  );
}
