import ClientGamedayReport from '@/components/ClientGamedayReport';

// prevent this page from being statically generated by vercel build
export const dynamic = 'force-dynamic';

// TODO: bunch of items...
// - start tracking ops
// - legend explaining trending icons and fire icon
// - collapsible sections
// - player first names
// - pitcher handedness
// - pitcher avg strikeouts?
// - AI summary section for how Jays have performed lately and how they did against the current opponent historically
// - remove redundant team abbreviations

export default function Index() {
  return <ClientGamedayReport />;
}
